version: 2
registries:
    dockerhub:
      type: docker-registry
      url: https://registry.hub.docker.com
      username: ${{ secrets.DHUBU }}
      password: ${{ secrets.DHUBP }}
updates:
    - package-ecosystem: "cargo"
      registries:
        - dockerhub
      directory: "/"
      schedule:
          interval: "daily"
          time: "10:00"
          timezone: "UTC"
      target-branch: "main"
      pull-request-branch-name:
        separator: "-"
      open-pull-requests-limit: 5
      assignees:
        - "deniskore"
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-minor"]
